CollegeEvents/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
    path('logins/',include('logins.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path, re_path, include
from . import views

app_name='forum'

urlpatterns = [
    path('', views.begin, name='begin'),

    path('display_ques/', views.display_ques, name='display_ques'),

    path('<int:question_id>/', views.display_ans, name='display_ans'),

    path('ask/', views.ask, name='ask'),

    path('questions/', views.ask_questions, name='ask_questions'),

    path('ind/', views.indd, name='indd'),

    ]

logins/urls.py
from django.urls import path
from . import views

app_name='logins'

urlpatterns = [

    path('',views.landing_page,name='landing_page'),

    path('choose/',views.choose,name='choose'),

    path('index/', views.index, name='index'),

    path('signup_view/',views.signup_view,name='signup_view'),

    path('login_view/', views.login_view, name='login_view'),

    path('logout_view/', views.logout_view, name='logout_view'),

    path('view_profile/', views.view_profile, name='view_profile'),

]

logins/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
#from events.models import Event
# Create your models here.

class SignupData(models.Model):
    ACCOUNT_TYPE = (
        ('part', 'Participant'),
        ('org', 'Organiser'),
        ('def', 'Default'),
    )
    user= models.OneToOneField(User, null=True, blank=True,on_delete=models.CASCADE)
    #events_related = models.ManyToManyField(Event, unique=False, blank=True)
    first_name=models.CharField(max_length=150, null=True, blank=True)
    last_name=models.CharField(max_length=150, null=True, blank=True)
    user_type = models.CharField(max_length=12, choices=ACCOUNT_TYPE, default='def')
    email=models.EmailField(null=True, blank=True, unique=False, default='abc@example.com')
    phone_num=models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username

    def getfullname(self):
        return str(self.first_name+' '+self.last_name)

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import User, UserProfile

ACCOUNT_TYPE = (
    ('part', 'Participant'),
    ('org', 'Organiser'),
    ('def', 'Default'),
)

class SignupForm(forms.ModelForm):
    # is_organizer = forms.BooleanField(required=False, label='Organiser Status')
    # is_participant = forms.BooleanField(required=False, label='Participant Status')
    user_type = forms.ChoiceField(choices = ACCOUNT_TYPE, label='Register as ')
    phone = forms.IntegerField(required=False, label='Phone Number')

    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','username','email','user_type','phone')

    def signup(self, request, user):
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        # user.userprofile.is_organizer = self.cleaned_data['is_organizer']
        # user.userprofile.is_participant = self.cleaned_data['is_participant']
        user.save()
        user.userprofile.user_type = self.cleaned_data['user_type']
        user.userprofile.phone = self.cleaned_data['phone']
        user.userprofile.save()

    # def __init__(self, *args, **kwargs):
    #     super(SignupForm, self).__init__(*args, **kwargs)
    #     self.fields['user_type'] = forms.ChoiceField(choices=ACCOUNT_TYPE)

class ContactForm(forms.Form):

    name = forms.CharField(required = True, max_length=120)
    email = forms.CharField(required = True)
    comment = forms.CharField(required = True, widget=forms.Textarea)

logins/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    #ID=forms.IntegerField(label='Enter ID')

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['usernamee'],
            self.cleaned_data['emaill'],
            self.cleaned_data['passwordd1'],
        )
        return user

logins/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.template import loader
from django.contrib.auth import login,logout
from django.contrib import messages
from events.models import Event
from django.contrib.auth.models import User
from django.conf import settings
from .forms import CustomUserCreationForm
from .models import *


def choose(request):
    return render(request,'logins/choose.html',{})


def index(request):
    return render(request,'logins/index.html',{})

def signup_view(request):
    if request.method=='POST':
        #form=CustomUserCreationForm(request.POST)#UserCreationForm(request.POST)
        #if form.is_valid():
            u = User.objects.create_user(
                request.POST['usernamee'],
                request.POST['emaill'],
                request.POST['passwordd1'],
            )
            s = SignupData()
            #user=form.save()
            #messages.success(request, 'Account created successfully')
            #login(request,user)
            s.user = u
            #rno=request.POST.get('rnum')#name='rnum'
            #author.rnum=rno
            s.first_name=request.POST.get('first_namee')
            s.last_name=request.POST.get('last_namee')
            s.user_type=request.POST.get('user_typee')
            s.phone_num=request.POST.get('phonee')
            s.save()
            return redirect('logins:login_view')
    else:
        form=CustomUserCreationForm(request.POST)#UserCreationForm()
    return render(request,'logins/signup_page.html',{'form':form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('events:index')
            #return render(request,'logins/login.html',{'name':user})

    else:
        form=AuthenticationForm()
    return render(request,'logins/login.html',{'form':form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('events:index')
    else:
        return render(request,'logins/logout_page.html',{})

def landing_page(request):
    return render(request, 'accounts/index.html',{})

def view_profile(request):
    events = Event.objects.all()
    username = request.user
    current_user = SignupData.objects.get(user=username)
    list = []
    for event in events:
        if event.participants.exists():
            list.append(event.name)
    return render(request, 'logins/view_profile.html', {'list':list})

logins/templates/logins/choose.html
 {% load crispy_forms_tags %} {% load i18n %}
 {% block content %}
<style>
@import url('https://fonts.googleapis.com/css?family=Quicksand');
html {
  padding-top: 100px;
  text-align: center;
  font-family: 'Quicksand', sans-serif;
  background-color: #273746;
  color: white;
}

button,
button::before,
button::after {
  border: 5px solid #0cf;
  padding: 0.5em 1em;
}

button {
  box-sizing: border-box;
  position: relative;
  overflow: hidden;
  cursor: pointer;
  font-weight: bold;
  font-size: 1.5em;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: transparent;
  background-color: transparent;
  -webkit-appearance: none;
  appearance: none;
}

button::before,
button::after {
  content: attr(data-text);
  position: absolute;
  right: -5px;
  left: -5px;
  transition: top 300ms;
}

button::before {
  top: 100%;
  color: #fff;
  background-color: #0cf;
}

button:hover::before,
button:focus::before {
  top: -5px;
}

button:active::before {
  color: gold;
}

button::after {
  top: -5px;
  color: #0cf;
}

button:hover::after,
button:focus::after {
  top: -100%;
}
h1{
  letter-spacing: 10px;
  font-weight: 300;
  font-size: 6em;
}
</style>

<body>

  <br><br><br><!--<br>-->
  <h1>COLLEGE EVENTS</h1>
  <br><br><br><!--<br>-->
<!--  <button data-text="ENTER" onclick="window.location.href='{% url 'account_signup' %}'">ENTER</button>
-->
  <button data-text="SignUp" onclick="window.location.href='{% url 'logins:signup_view' %}'">SignUp</button>
  <button data-text="SignIn" onclick="window.location.href='{% url 'logins:login_view' %}'">LogIn</button>
  <button data-text="Home" onclick="window.location.href='{% url 'events:index' %}'">Home</button>

</body>
{% endblock content %}

logins/templates/logins/index.html
<h1>Hello world!!!</h1>

logins/templates/logins/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head><meta charset="utf-8">
<title>Signup</title>
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/style.css">
<link rel="shortcut icon" type="image/ico" href="/static/images/favicon.ico">

</head>



<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/events/">
    <img src="/static/images/logo.png" width="200" height="40">
  </a>
  <div class="collapse navbar-collapse" id="nav-content">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="/events/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/events/about/">About</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/forum/">Forum</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/contact/">Contact</a>
      </li>
    </ul>

      <ul class="navbar-nav ml-auto">
        <!--<li class="nav-item active"><a class="nav-link" href="/accounts/login/">Signin</a></li>
-->
          <li class="nav-item active"><a class="nav-link" href="{% url 'logins:login_view' %}">Signin</a></li>
      </ul>

  </div>
</nav>
<br>
<br>
<br>
<br>
<center>
    <h1>Login</h1>
</center>
<br>
<br>

<center>          <h5><p>Doesn't have an account? Then please <a href="{% url 'logins:signup_view' %}">sign up</a>.</p>
</h5>
</center>

<br>

<!--    <form class="site-form" action="{% url 'logins:login_view' %}" method="POST"><!--TO logins/signup_view-->
    <form class="site-form" action="{% url 'logins:login_view' %}" method="POST"><!--TO logins/signup_view-->

    {% csrf_token %}
<!--    <div class="col-md-3"></div>
  <div class="col-md-6">
-->
        <center>
          <h2>
    {{form|crispy}}
          </h2>
        </center>
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
  <!--</div>-->
        <br>
        <br>
        <center>

      <button type="submit" class="btn btn-primary">Sign In »</button>
        </center>
    </form>
{% if name %}
{{ name }}
{% endif %}
</body>
</html>

logins/templates/logins/login_page.html
<h1>Welcome to login page!!!</h1>

logins/templates/logins/logout_page.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<br><br><br><br>
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h1>{% trans "Sign Out" %}</h1>
    <p>{% trans 'Are you sure you want to sign out?' %}</p>
<!--    <form method="post" action="{% url 'account_logout' %}">
    -->
          <form method="post" action="{% url 'logins:logout_view' %}">

      {% csrf_token %}
      <!--{% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
      {% endif %}-->
      <button type="submit" class="btn btn-dark">Sign Out</button>
    </form>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}

logins/templates/logins/signup.html
<h1>SignUp</h1>
<form class="site-form" action="" method="POST"><!--TO logins/signup_view-->

    {% csrf_token %}
    <input type="text" name="namee" required>
    {{form.as_p}}
    <h4>Roll Number:</h4>
    <input type="text" name="rnum" value="Enter Roll Number:" required>
    <input type="submit" value="Signup">

</form>

logins/templates/logins/signup_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head><meta charset="utf-8">
<title>Signup</title>
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/style.css">
<link rel="shortcut icon" type="image/ico" href="/static/images/favicon.ico">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/events/">
    <img src="/static/images/logo.png" width="200" height="40">
  </a>
  <div class="collapse navbar-collapse" id="nav-content">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="/events/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/events/about/">About</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/forum/">Forum</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/contact/">Contact</a>
      </li>
    </ul>

      <ul class="navbar-nav ml-auto">
<!--        <li class="nav-item active"><a class="nav-link" href="/accounts/login/">Signin</a></li>
-->
        <li class="nav-item active"><a class="nav-link" href="{% url 'logins:login_view' %}">Signin</a></li>
      </ul>

  </div>
</nav>

  <br>

<br><br><br><br>
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h1>Sign Up</h1>

<!--    <p>Already have an account? Then please <a href="/accounts/login/">sign in</a>.</p>
<!--    <form class="signup" id="signup_form" method="post" action="/accounts/signup/">
-->
          <p>Already have an account? Then please <a href="{% url 'logins:login_view' %}">sign in</a>.</p>

          <form class="signup" id="signup_form" method="post" action="{% url 'logins:signup_view' %}">

        {% csrf_token %}



    <div id="div_id_username" class="form-group">

            <label for="id_username" class="col-form-label  requiredField">
                Usernames<span class="asteriskField">*</span>
            </label>








                <div class="">
                    <input type="text" name="usernamee" placeholder="Username" autofocus="autofocus" minlength="5" maxlength="150" class="textinput textInput form-control" required="" id="id_username">

                </div>


    </div>

    <div id="div_id_email" class="form-group">

            <label for="id_email" class="col-form-label  requiredField">
                E-mail<span class="asteriskField">*</span>
            </label>

                <div class="">
                    <input type="email" name="emaill" placeholder="E-mail address" class="textinput textInput form-control" required="" id="id_email">

                </div>

    </div>

      <div class="row">
        <div class="col">

    <div id="div_id_first_name" class="form-group">

            <label for="id_first_name" class="col-form-label ">
                First name
            </label>

                <div class="">
                    <input type="text" name="first_namee" maxlength="30" class="textinput textInput form-control" id="id_first_name">

                </div>

    </div>


</div>
        <div class="col">

    <div id="div_id_last_name" class="form-group">

            <label for="id_last_name" class="col-form-label ">
                Last name
            </label>

                <div class="">
                    <input type="text" name="last_namee" maxlength="150" class="textinput textInput form-control" id="id_last_name">

                </div>

    </div>


</div>
      </div>
      <div class="row">
        <div class="col">

    <div id="div_id_user_type" class="form-group">

            <label for="id_user_type" class="col-form-label  requiredField">
                Register as <span class="asteriskField">*</span>
            </label>

                <div class="">
                    <select name="user_typee" class="select form-control" id="id_user_type">
  <option value="part">Participant</option>

  <option value="org">Organiser</option>

  <option value="def">Default</option>

</select>
                </div>

    </div>

</div>
        <div class="col">

    <div id="div_id_phone" class="form-group">

            <label for="id_phone" class="col-form-label ">
                Phone Number
            </label>

                <div class="">
                    <input type="number" name="phonee" class="numberinput form-control" id="id_phone">

                </div>

    </div>

</div>
      </div>

    <div id="div_id_password1" class="form-group">

            <label for="id_password1" class="col-form-label  requiredField">
                Password<span class="asteriskField">*</span>
            </label>
                <div class="">
                    <input type="password" name="passwordd1" placeholder="Password" class="textinput textInput form-control" required="" id="id_password1">

                </div>


    </div>

    <div id="div_id_password2" class="form-group">

            <label for="id_password2" class="col-form-label  requiredField">
                Password (again)<span class="asteriskField">*</span>
            </label>

                <div class="">
                    <input type="password" name="password2" placeholder="Password (again)" class="textinput textInput form-control" required="" id="id_password2">

                </div>


    </div>

      <br>

      <button type="submit" class="btn btn-primary">Sign Up »</button>
    </form>
  </div>
  <div class="col-md-3"></div>
</div>

  <footer class="footer" style="position:relative; bottom:0; width:100%; height:60px;background-color:black;">
    <div class="container">
      <span class="text-light">© Copyright 2018</span>
    </div>
  </footer>

<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<!-- Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Initialize Bootstrap functionality -->

<script>
  // Initialize tooltip component
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // Initialize popover component
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
  function goBack() {
      window.history.back()
  }
</script>

</body>
</html>