CollegeEvents/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
    path('logins/',include('logins.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.view_profile, name='view_profile'),
    path('accounts/login/events/', views.events_redirect, name='events_redirect'),
    path('accounts/signup/events/', views.signup_redirect, name='signup_redirect'), #
]

events/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('create/', views.create, name='create'),

    path('select_club/',views.select_club,name='select_club'),
    path('<int:event_id>/', views.detail_of_event, name='detail_of_event'),

    path('home/', views.index, name='home'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete, name='delete'),
    re_path(r'^(?P<slug>[\w-]+)/update/$', views.update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/view_participants/$', views.view_participants, name='view_participants'),
    re_path(r'^(?P<slug>[\w-]+)/notify/$', views.create_notification, name='create_notification'),


    #re_path(r'^(?P<slug>[\w-]+)/detail_of_event/$', views.detail_of_event, name='detail_of_event'),


    re_path(r'^(?P<slug>[\w-]+)/participate/$', views.participate, name='participate'),
    re_path(r'^(?P<slug>[\w-]+)/gallery/$', views.view_gallery, name='view_gallery'),
    #path('events/')
]

forum/urls.py
from django.urls import path, re_path, include
from . import views

app_name='forum'

urlpatterns = [
    path('', views.begin, name='begin'),

    path('display_ques/', views.display_ques, name='display_ques'),

    path('<int:question_id>/', views.display_ans, name='display_ans'),

    path('ask/', views.ask, name='ask'),

    path('questions/', views.ask_questions, name='ask_questions'),

    path('ind/', views.indd, name='indd'),

    ]

logins/urls.py
from django.urls import path
from . import views

app_name='logins'

urlpatterns = [

    path('',views.landing_page,name='landing_page'),

    path('choose/',views.choose,name='choose'),

    path('index/', views.index, name='index'),

    path('signup_view/',views.signup_view,name='signup_view'),

    path('login_view/', views.login_view, name='login_view'),

    path('logout_view/', views.logout_view, name='logout_view'),

    path('view_profile/', views.view_profile, name='view_profile'),

]

templates/base.html
{# if page has scorlling extend this else extend base_sticky.html #}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta charset="utf-8">
<title>{% block head_title %}College Events{% endblock head_title %}</title>
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /></link>
<link rel="shortcut icon" type="image/ico" href="{%  static 'images/favicon.ico' %}" /></link>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css" /></link>

<body>
  {% include 'navbar.html' %}
  <br/>
  {% block content %}
  {% endblock %}
  <footer class="footer" style="position:relative; bottom:0; width:100%; height:60px;background-color:black;">
    <div class="container">
      <span class="text-light">&copy; Copyright 2018</span>
    </div>
  </footer>
</body>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<!-- Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Initialize Bootstrap functionality -->

<script>
  // Initialize tooltip component
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // Initialize popover component
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
  function goBack() {
      window.history.back()
  }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
</html>

templates/base_no_nav.html
{# if page there is no scorlling extend this else extend base_scroll.html #}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta charset="utf-8">
<title>{% block head_title %}College Events{% endblock head_title %}</title>
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /></link>
<link rel="shortcut icon" type="image/ico" href="{%  static 'images/favicon.ico' %}" /></link>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
  <br/>
  {% block content %}
  {% endblock %}
</body>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<!-- Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Initialize Bootstrap functionality -->

<script>
  // Initialize tooltip component
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // Initialize popover component
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
  function goBack() {
      window.history.back()
  }
</script>
</html>

templates/base_scroll.html
{# if page has scorlling extend this else extend base_sticky.html #}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta charset="utf-8">
<title>{% block head_title %}College Events{% endblock head_title %}</title>
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /></link>
<link rel="shortcut icon" type="image/ico" href="{%  static 'images/favicon.ico' %}" /></link>

<body>
  {% include 'navbar.html' %}
  <br/>
  {% block content %}
  {% endblock %}
  <footer class="footer" style="position:relative; bottom:0; width:100%; height:60px;background-color:black;">
    <div class="container">
      <span class="text-light">&copy; Copyright 2018</span>
    </div>
  </footer>
</body>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<!-- Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Initialize Bootstrap functionality -->

<script>
  // Initialize tooltip component
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // Initialize popover component
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
  function goBack() {
      window.history.back()
  }
</script>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="{% url 'logins:landing_page' %}">
    <img src="{% static 'images/logo.svg' %}" width="60" height="30" class="d-inline-block align-center" alt="">
    Evention
  </a>
  <div class="collapse navbar-collapse" id="nav-content">
    <ul class="navbar-nav mr-auto">
      {% url 'home' as home %} {% url 'about' as about %} {% url 'forum' as forum %} {% url 'contact' as contact %}
      <li  class="nav-item active" >
        <a class="nav-link" href="{% url 'events:index' %}">Home</a>
      </li>
      <li class="nav-item active" >
        <a class="nav-link" href="{% url 'events:about' %}">About</a>
      </li>
      <li  class="nav-item active" >
        <a class="nav-link" href="{% url 'forum:begin' %}">Forum</a>
      </li>
      <li  class="nav-item active" >
        <a class="nav-link" href="{% url 'accounts:contact' %}">Contact</a>
      </li>
    </ul>
    {% if request.user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'logins:view_profile' %}">View Profile</a>
          <a class="dropdown-item" href="{% url 'events:select_club' %}">View by Clubs</a>
          {% if  request.user.is_superuser or request.user.signupdata.user_type == 'org' %}
            <a class="dropdown-item" href="{% url 'events:create' %}">Create Event</a>
          {% endif %}
          <div class="dropdown-divider"></div>
<!--          <a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a>
-->
                    <a class="dropdown-item" href="{% url 'logins:logout_view' %}">Sign out</a>

        </div>
      </li>
    </ul>
    {% else %}
      <ul class="navbar-nav ml-auto">
<!--        <li class="nav-item active"><a class="nav-link" href="{% url 'account_login' %}">Signin</a></li>
    -->
                <li class="nav-item active"><a class="nav-link" href="{% url 'logins:signup_view' %}">SignUp</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'logins:login_view' %}">Signin</a></li>

      </ul>
    {% endif %}
  </div>
</nav>