CollegeEvents/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
    path('logins/',include('logins.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('create/', views.create, name='create'),

    path('select_club/',views.select_club,name='select_club'),
    path('<int:event_id>/', views.detail_of_event, name='detail_of_event'),

    path('home/', views.index, name='home'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete, name='delete'),
    re_path(r'^(?P<slug>[\w-]+)/update/$', views.update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/view_participants/$', views.view_participants, name='view_participants'),
    re_path(r'^(?P<slug>[\w-]+)/notify/$', views.create_notification, name='create_notification'),


    #re_path(r'^(?P<slug>[\w-]+)/detail_of_event/$', views.detail_of_event, name='detail_of_event'),


    re_path(r'^(?P<slug>[\w-]+)/participate/$', views.participate, name='participate'),
    re_path(r'^(?P<slug>[\w-]+)/gallery/$', views.view_gallery, name='view_gallery'),
    #path('events/')
]

forum/urls.py
from django.urls import path, re_path, include
from . import views

app_name='forum'

urlpatterns = [
    path('', views.begin, name='begin'),

    path('display_ques/', views.display_ques, name='display_ques'),

    path('<int:question_id>/', views.display_ans, name='display_ans'),

    path('ask/', views.ask, name='ask'),

    path('questions/', views.ask_questions, name='ask_questions'),

    path('ind/', views.indd, name='indd'),

    ]

events/models.py
from django.db import models
from django.utils.text import slugify
from datetime import datetime
from django.conf import settings
from django.db.models.signals import pre_save
from django.utils.timezone import now as timezone
from django.urls import reverse
from logins.models import SignupData
import random, string
from . utility import unique_slug_generator

def upload_location(instance, filename):
    return '%s/%s' %(instance.tag, filename)

# Create your models here.
class Event(models.Model):
    CLUB_LIST = (
        ('Swayam', 'Swayam'),
        ('EcoClub', 'Eco Club'),
        ('ArtsClub', 'Arts club'),
        ('Abhinay', 'Abhinay'),
        ('ThemeBallet', 'Theme Ballet'),
        ('VCETalkies', 'Vasavi talkies'),
        # ('it', 'Dept. Of Information Technology'),
        ('CSI', 'CSI')
    )
    name = models.CharField(max_length = 32)
    tag = models.SlugField(max_length=50)
    club = models.CharField(max_length=12, choices=CLUB_LIST)#, default='it')
    description = models.TextField(default = '')
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field="width_field", height_field="height_field")
    height_field = models.IntegerField(default=300)
    width_field = models.IntegerField(default=600)
    date = models.DateTimeField(default=datetime.now())
    organiser = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)#references to User model not UserProfile
    contact = models.EmailField(default="abc@gmail.com")
    participants = models.ManyToManyField(SignupData, default=1, unique=False, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.tag:
            #if urltag is not existing create a unique url
            self.tag = unique_slug_generator(self)
        super(Event, self).save()

    def get_absolute_url(self):
        #to get url for events with slugs, since pk is not used
        return reverse("events:detail", kwargs={"slug": self.tag})

events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "name",
            "tag",
            "club",
            "description",
            "image",
            "date",
            "organiser",
            "contact",
        ]

class NotificationForm(forms.Form):

    subject = forms.CharField(max_length=100)
    body = forms.CharField(required = True, widget=forms.Textarea)

events/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Event
from logins.models import SignupData
from .forms import EventForm, NotificationForm
from .utility import send_whatsapp_message
import os
from selenium import webdriver

# Create your views here.
def about(request):
    return render(request, 'events/about.html')

def index(request):
    events = Event.objects.all().order_by('-date')
    return render(request, 'events/index.html', {'event_list': events})

def home(request):
    events = Event.objects.all().order_by('-date')
    return render(request, 'events/index.html', {'event_list': events})


def select_club(request):
    if request.method=='POST':
        club_name=request.POST.get('club_name')
        list_of_events=Event.objects.filter(club=club_name)
        return render(request,'events/display_events_under_club.html',{'list_of_events':list_of_events})
    else:
        return render(request,'events/select_club.html',{})
    pass




def detail_of_event(request,event_id):
    event=get_object_or_404(Event,pk=event_id)
    return render(request,'events/detail.html',{'event':event})


def detail(request, slug):
    event = get_object_or_404(Event, tag=slug)
    participants = event.participants.all()
    return render(request, 'events/detail.html', {'event':event})


@login_required(login_url="logins:login_view")
def view_participants(request, slug):
    event = get_object_or_404(Event, tag=slug)
    participants = event.participants.all()
    return render(request,'events/participants_list.html', {'participants':participants})

#Creating an event
@login_required(login_url="logins:login_view")
def create(request):
    form = EventForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #messages.success(request, "Event Created") #It is not rendered as it was not fitting with the template
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        pass
        #messages.error(request, "Could not create Event")
    return render(request, 'events/createform.html', {'form': form})

@login_required(login_url="logins:login_view")
def create_notification(request, slug):
    event = get_object_or_404(Event, tag=slug)
    title = 'Contact'
    form = NotificationForm(request.POST or None)
    confirm_message = None
    event = get_object_or_404(Event, tag=slug)
    participants = event.participants.all()
    from_email = settings.EMAIL_HOST_USER
    to_list = ['iam191911918114@gmail.com']
    for p in participants:
        to_list.append(p.email)
    print(to_list)

    if form.is_valid():

        body = form.cleaned_data['body']
        subject = 'Message from  from event '
        print(subject)
        message = 'asfdfdf\n'
        #send_whatsapp_message(message)
        send_mail(subject, body, from_email, to_list, fail_silently=True)
        title = "Success!"
        confirm_message = "All the participants of this events are notified."
        form = None
    context = {'title': title, 'form': form, 'confirm_message': confirm_message}
    return render(request, 'events/notifications.html', context)


#Updating an event
@login_required(login_url="logins:login_view")
def update(request, slug=None):
    event = Event.objects.get(tag=slug) #checking if logged in user is the organiser of the event
    organiser_of_event = event.organiser
    instance = get_object_or_404(Event, tag=slug)
    form = EventForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #messages.success(request, "Event details updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        pass
        #messages.error(request, "Could not update Event")

    context = {
        'name' : instance.name,
        'description' : instance.description,
        'date' : instance.date,
        'organiser' : instance.organiser,
        'contact' : instance.contact,
        'form' : form,
        'organiser_of_event' : organiser_of_event,
    }
    return render(request, 'events/updateform.html', context)

@login_required(login_url="logins:login_view")
def delete(request, slug=None):
    event = Event.objects.get(tag=slug)
    organiser_of_event = event.organiser
    if request.user == organiser_of_event:
        instance = get_object_or_404(Event, tag=slug)
        instance.delete()
        messages.success(request, "Event deleted")
        return redirect('events:index')
    else:
        return render(request, 'events/delete.html')

def participate(request, slug):
    event = Event.objects.get(tag=slug)
    username = request.user
    current_user = SignupData.objects.get(user=username)
    event.participants.add(current_user)
    return render(request, 'events/success_participation.html',{})

def view_gallery(request, slug):
    event = get_object_or_404(Event, tag=slug)
    participants = event.participants.all()
    return render(request,'events/view_gallery.html', {'participants':participants, 'event':event})

templates/events/about.html
{% extends 'base.html' %} {% block content %}
<br>
<div class="container" style="min-height:100%;">
  <div class="jumbotron">
    <h1>About the website</h1>
    <hr class="my-4">
    <p class="lead">College Events website is a web-application which displays the current departmental, club and community events happening at Vasavi College of Engineering. The application is responsive, robust and reliable and is developed to overcome the obfuscation
      in the current college website and enhance the experience of its users.</p><br/>
    <p class="lead">The project is divided in three applications - accounts, events and forum. The accounts application handles all the functions related to user login, signup, password validation, sessions handling, email confirmation, etc. This is provided by allauth
      library, which is installed as an application in this project. The events application deals with the events. This application allows authenticated users to create, view, update and delte an event. Every event is associated with an organiser. The
      user has an option to get notification to their email whenever there is an update for an event he chooses. The forum app is a section where users can ask questions and give answers to an event. Only verified users are allowed to post questions and
      answers.
    </p><br/>
    <p class="lead">The back-end of the web-application is developed using Django2.0 framework and few utility functions were written in Python3. The database used for the project is SQLite, which is the default database for Django. The front-end of the web-application
      is developed using Bootstrap4, HTML5 and CSS3.
    </p><br/>
  </div>
</div>
<div class="card text-center">
  <div class="card-header">

  </div>
  <div class="card-body">
    <h4 class="card-title"> Source code </h4>
    <p class="card-text">Link to the Github repository of the project</p>
    <a href="https://github.com/1919kiran/College-Events-A" class="btn btn-primary" target="_blank">Visit</a>
  </div>
</div>
<br>
<br>
<h4 class="text-center">Developers</h4>
<hr>
<br>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Sai Kiran</h5>
        <p class="card-text"><i>BE 3/4-IT 1602-15-737-039</i></p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Abishek Vanam</h5>
        <p class="card-text"><i>BE 3/4-IT 1602-15-737-002</i></p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Govind Goud</h5>
        <p class="card-text"><i>BE 3/4-IT 1602-15-737-013</i></p>
      </div>
    </div>
  </div>
  <div class="col-sm-1"></div>
</div>
<br><br> {% endblock content %}

templates/events/createform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <br/><br/><br/>
  <div class="content" style="min-height:100%;max-width:100%;">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <form method = 'POST' action="#" enctype="multipart/form-data">{% csrf_token %}
          {{ form|crispy }}
          <br/>
          <input type='submit' value='Create Event' class="btn btn-primary"/>
          <br>
          <br>
          <br>
          <br>
        </form>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
{% endblock content %}

templates/events/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Only organiser can delete the event -->
  <br><br>
  <div class="card text-center" style="min-height:100%;max-width:100%;">
    <div class="card-header">
      DELETE ERROR
    </div>
    <div class="card-body">
      <h5 class="card-title">You are not organiser of this event.</h5>
      <p class="card-text">An event can be deleted only by its organiser.</p>
      <button class="btn btn-primary" onclick="goBack()">Go back</button>
    </div>
  </div>
{% endblock content %}

templates/events/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{ instance.name }}{% endblock head_title %}
{% block content %}
  <br/><br/><br/>
  <div class="row" style="min-height:100%;max-width:100%;">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <a class="lead">Name: </a><a>{{ event.name|linebreaks }}</a><br>
      <a class="lead">Club: </a><a>{{ event.club|linebreaks }}</a><br>
      <a class="lead">Description: </a><a>{{ event.description|linebreaks }}</a><br>
      <a class="lead">Date: </a><a>{{ event.date|linebreaks }}</a><br>
      <a class="lead">Organiser: </a><a>{{ event.organiser|linebreaks }}</a><br>
      <a class="lead">Contact: </a><a>{{ event.contact|linebreaks }}</a><br>

      <br><br><br>
      <div class="row">
        <div class="col-md-3">
          <input type="submit" class="btn btn-primary btn-lg btn-block" onclick="location.href='{% url "events:participate" event.tag %}'" value="Partictpate" ></input>
        </div>
          <div class="col-md-3">
            <input type="submit" class="btn btn-primary btn-lg btn-block" onclick="location.href='{% url "events:view_participants" event.tag %}'" value="View Participants" ></input>
          </div>
          <div class="col-md-3">
            <input type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='{% url "events:create_notification" event.tag %}'" value="Create Notification" /></input>
          </div>
          <div class="col-md-3">
            <input type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='{% url "events:view_gallery" event.tag %}'" value="View Gallery" /></input>
          </div>
      </div>
      <br><br><br>
    </div>
    <div class="col-md-3"></div>

  </div>

{% endblock content %}
{% block footer %}
<footer class="footer" style="position: fixed;bottom:0em;background-color: black">
  <div class="container">
    <span class="text-muted">&copy; Copyright 2018.</span>
  </div>
</footer>
{% endblock footer %}
onclick="location.href='{% url "events:view_participants" event.tag %}'

templates/events/display_events_under_club.html
{% extends 'base.html' %}
{% block head_title %}{{ instance.name }}{% endblock head_title %}
{% block content %}
<br>
<br>
<br>
<br>



<div class="container" style="min-height:100%;">
{% if list_of_events %}
<ul>
{% for event in list_of_events %}
    <h3>
      <center>
        <div class="card" style="width: 18rem;">
          {% if event.image %}
            <img class="card-img-top" src="{{ event.image.url }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{event.name}}</h5>
            <p class="card-text">{{event.description|truncatechars:50}}</p>
            <a href="{% url 'events:detail_of_event' event.id %}" class="btn btn-primary">Go to event</a>
          </div>
        </div>
      </center>
      <br><br>
    </h3>

<!--
<a href="">{{event.name}}</a>
-->
{% endfor %}
</ul>
{% else %}
<h2>No events to display under this club!!!</h2>
{% endif %}
<!--
  <button data-text="<<Back" onclick="window.location.href='{% url 'events:select_club' %}'">Go Back</button>-->
<button onclick="window.location.href='{% url 'events:select_club' %}'" class="btn btn-primary">Go back</button>
<br>
<br>
</div>

{% endblock content %}

templates/events/index.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<style>
  body {
    margin: 0;
    padding: 0;
    perspective: 1px;
    transform-style: preserve-3d;
    height: 100%;
    overflow-y: scroll;
    overflow-x: hidden;
    font-family: Nunito;
  }

  h1 {
    font-size: 250%
  }

  p {
    font-size: 140%;
    line-height: 150%;
    color: white;
  }

  body, html{
    min-height: 100%
    height:100%;
    margin:0;
    font-size:16px;
    font-family: 'Nunito';
    font-weight:400;
    line-height:1.8em;
    color:#666;
  }

  .pimg1, .pimg2, .pimg3, .pimg{
    position:relative;
    opacity:0.70;
    background-position:center;
    background-size:cover;
    background-repeat:no-repeat;
    background-attachment:fixed;
  }

  .pimg{
    background-image:url({% static 'images/background.gif'%});
    min-height:100%;
  }

  .pimg1{
    background-image:url({% static 'images/image3.jpg'%});
    min-height:100%;
  }

  .pimg2{
    background-image:url({% static 'images/image2.jpg'%});
    min-height:400px;
  }

  .pimg3{
    background-image:url({% static 'images/image1.jpg'%});
    min-height:400px;
  }

  .section{
    text-align:center;
    text-transform:uppercase;
    padding:50px 80px;
  }
  .section p{
    text-align:center;
    text-transform:lowercase;
    padding:50px 80px;
  }

  .section-light{
    background-color:#f4f4f4;
    color:#666;
  }

  .section-dark{
    background-color:#282e34;
    color:#ddd;
  }

  .ptext{
    position:absolute;
    top:50%;
    width:100%;
    text-align:center;
    color:#000;
    font-size: 7vh;
    letter-spacing:5px;
    text-transform:uppercase;
  }
  .ptext .border{
    -webkit-transform:scale(1.1,1.3);
    background-color:transparent;
    letter-spacing: 10px;
    color:#fff;
    padding: 40px;
  }

  .ptext .border: hover{
    all:inherit;
    -webkit-transform:scale(1.1,1.3);
    background-color:grey;
    color:#fff;
    padding:40px;
  }

  .ptext .border.trans{
    background-color:transparent;
    transition-duration: 1s;
    padding:40px;
  }

  .ptext .border.trans:hover{
    background-color:black;
    color: white;
    -webkit-transtion: all 2s ease-in-out;
    padding:60px;
  }

  @media(max-width:568px){
    .pimg1, .pimg2, .pimg3, .pimg{
      background-attachment:scroll;
    }
  }
</style>
<!-- Displays error messages if any -->

<div class="pimg">
  <div class="ptext">
    <span class="border">
        Events
      </span>
  </div>
</div>
{% for event in event_list %}
  <div class="{% cycle 'pimg1' 'pimg2' 'pimg3'%}">
    <a href="{{ event.get_absolute_url }}">
      <div class="ptext">
        <span class="border trans" style="text-transform:uppercase";>
            {{event.name}}
          </span>
      </div>
    </a>
  </div>
  <section class="section section-dark" >
    <h2><u>{{event.name}}</u></h2>
    <br/>
    <p style="text-align:justify;">{{event.description|truncatechars:300 }}</p>
  </section>

{% endfor %}

{% endblock content %}

templates/events/notifications.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}{% trans "Contact" %}{% endblock %}
<style>
</style>

<body >
  <br/><br/><br/>
  <div class="row" style="min-height:100%;max-width:100%;">
    <div class="col-md-3"></div>
    <div class="col-sm-6">
      {% if not confirm_message %}
      <h1>{% trans "Create your Notification" %}</h1>
      {% endif %}
      <br>
      {% if confirm_message %}
      <br>
      <h1><strong>{{ title }}</strong></h1>
      <br>
      <h3>{{ confirm_message }}</h3>
      {% endif %}
      {% if form %}
      <form method = 'POST' action = ''> {% csrf_token %}
        {{ form|crispy }}
        <input type = "submit" value = 'Submit' class = 'btn btn-primary'/>
      </form>
      {% endif %}
    </div>
    <div class="col-md-3"></div>
  </div>
</body>

{% endblock content %}

templates/events/participants_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="min-height:100%;">
  <br><br><br><br>
  <h2>Participants List</h2>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>User Type</th>
        <th>Phone Number</th>
      </tr>
    </thead>
    <tbody>
      {% for participant in participants %}
        <tr>
          <td>{{ participant.user }}</td>
          <td>{{ participant.email }}</td>
          <td>{{ participant.first_name }}</td>
          <td>{{ participant.last_name }}</td>
          <td>{{ participant.user_type }}</td>
          <td>{{ participant.phone_num }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>

{% endblock %}

templates/events/select_club.html
{% extends 'base.html' %}
{% block head_title %}{{ instance.name }}{% endblock head_title %}

{% block content %}
<br>
<br>
<br>

<div class="container" style="min-height:100%;">
  <form action="{% url 'events:select_club' %}" method="POST">
      {% csrf_token %}
      <label class="col-form-label  requiredField">
                                      Select club <span class="asteriskField">*</span>
                                  </label>
              <div class="">
                  <br>
                  <br>
                              <select name="club_name" class="select form-control" id="">

                  <option value="Swayam">Swayam</option>

                        <option value="EcoClub">Eco Club</option>

                        <option value="ArtsClub">Arts Club</option>

                        <option value="Abhinay">Abhinay</option>

                        <option value="ThemeBallet">Theme Ballet</option>

                        <option value="VCETalkies">Vasavi Talkies</option>

                        <option value="CSI">CSI</option>
                              </select>
              </div>
      <br>
      <br>
      <button type="submit" class="btn btn-primary">Search</button>
  </form>
</div>

{% endblock content %}

templates/events/success_participation.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="min-height:100%;">
  <br><br><br>
  <h1>Success!</h1>
  <br>
  <h2>You have been added to participants list<h2>
  <br><br>
  <button class="btn btn-primary" onclick="goBack()">Go back</button>
</div>
{% endblock %}

templates/events/updateform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Only organiser can update the event -->
{% if request.user == organiser_of_event %}
  <br/><br/><br>
  <div class="row" style="min-height:100%;max-width:100%;">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <form method = 'POST' action="#">{% csrf_token %}
        {{ form.name|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        {{ form.organiser|as_crispy_field }}
        {{ form.date|as_crispy_field }}
        {{ form.contact|as_crispy_field }}
        <br>
        <input type='submit' value='Update Event' class="btn btn-primary"/>
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
  {% else %}
  <br><br>
  <div class="card text-center">
    <div class="card-header">
      UPDATE ERROR
    </div>
    <div class="card-body">
      <h5 class="card-title">You are not organiser of this event.</h5>
      <p class="card-text">An event can be updated only by its organiser.</p>
      <button class="btn btn-primary" onclick="goBack()">Go back</button>
    </div>
  </div>
{% endif %}
{% endblock content %}

templates/events/view_gallery.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container" style="min-height:100%;">

  <br><br><br>

  <div class="container gallery-container">
    <h1 class="text-center">Gallery</h1>
    <br>
    <h4 class="page-description text-center">{{event.name}}</h4>
    <br><br>
    <div class="tz-gallery">
      <div class="row mb-3">
        <div class="col-md-4">
          <div class="card">
            <a class="lightbox" href="{% static 'images/image1.jpg' %}">
              <img src="{% static 'images/image1.jpg' %}" alt="Park" class="card-img-top">
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <a class="lightbox" href="{% static 'images/image2.jpg' %}">
              <img src="{% static 'images/image2.jpg' %}" alt="Park" class="card-img-top">
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <a class="lightbox" href="{% static 'images/image3.jpg' %}">
              <img src="{% static 'images/image3.jpg' %}" alt="Park" class="card-img-top">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}