CollegeEvents/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
    path('logins/',include('logins.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path, re_path, include
from . import views

app_name='forum'

urlpatterns = [
    path('', views.begin, name='begin'),

    path('display_ques/', views.display_ques, name='display_ques'),

    path('<int:question_id>/', views.display_ans, name='display_ans'),

    path('ask/', views.ask, name='ask'),

    path('questions/', views.ask_questions, name='ask_questions'),

    path('ind/', views.indd, name='indd'),

    ]

forum/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text=models.CharField(max_length=300)
    question_pub_date = models.DateTimeField('date published',default='0')
    asked_by=models.CharField(max_length=100)

    def __str__(self):
        return self.question_text


class Answer(models.Model):
#    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    answer_text=models.CharField(max_length=500)
    question_id_of_answer=models.IntegerField(default=0)
    answer_pub_date=models.DateTimeField('date published',default='0')
    answered_by=models.CharField(max_length=100)
    #votes=models.IntegerField(default=0)

    def __str__(self):
        return self.answer_text

forum/forms.py
from django import forms

class QuestionForm(forms.Form):
    question_text=forms.CharField(max_length=300)

forum/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from. import mypythoncode
from .models import *
from .forms import *
from django.utils import timezone
# Create your views here.


def indd(request):
    return render(request,'forum/ind.html',{})


def begin(request):
    return render(request,'forum/start_page.html',{})
    pass


def display_ques(request):
    #all_questions=Question.objects.all()
    all_questions = Question.objects.order_by('-question_pub_date')
    context={'all_questions':all_questions}
    return render(request,'forum/display_questions.html',context)
    pass

@login_required(login_url="logins:login_view")
def display_ans(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        answer = request.POST.get('answer')
        obj = Answer(
            answer_text=answer,
            question_id_of_answer=question_id,
            answer_pub_date=timezone.now(),
            answered_by=request.user.username
        )
        obj.save()

    answers = Answer.objects.filter(question_id_of_answer=question_id)
    context = {'question': question, 'answers': answers}

    return render(request, 'forum/display_answers.html', context)



@login_required(login_url="logins:login_view")
def ask(request):
    return render(request, 'forum/ask_questions.html', {})

def ask_questions(request):
    if request.method == 'POST':
        form=QuestionForm(request.POST)
        question = request.POST.get('question','')
        obj=Question(question_text=question,
                     question_pub_date=timezone.now(),
                     asked_by=request.user.username
                )
        obj.save()
        all_questions = Question.objects.order_by('-question_pub_date')
        context = {'all_questions': all_questions}
        return render(request,'forum/display_questions.html',context)
    return render(request,'forum/start_page.html',{})

templates/forum/ask_questions.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-2" ></div>
  <div class="col-md-8">
    <form id="myform" action="{% url 'forum:ask_questions' %}" class="fs-form fs-form-full" autocomplete="off" method="POST">
      {% csrf_token %}
      <br><br>
      <center>
        <h2>Enter the question:</h2>
        <input type="text" class="form-control" id="q2" name="question" placeholder="Enter your question"/>
        <br><br>
        <button class="btn btn-primary" type="submit" %}>Ask!</button>
      </center>
    </form>
  </div>
</div>
{% endblock content%}

templates/forum/display_answers.html
{% extends 'base.html' %}

{% block content %}
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <br><br><br>
    <h1>{{ question.question_text }}</h1>
    <p class="text-right">asked by: {{question.asked_by}}</p>
    <p class="text-right">on: {{question.question_pub_date}}</p>
    <br><br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if answers %}

    <ul>
    {% for answer in answers %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container" >
        <p class="lead">{{ answer.answer_text }}</p>
        <hr class="my-4">
        <p class="text-right">answered by: {{answer.answered_by}}</p>
        <p class="text-right">on: {{answer.answer_pub_date}}</p>
      </div>
    </div>
    {% endfor %}
    </ul>
    {% else %}
        <h2>No answers to display</h2>
    {% endif %}


    <div class="form-group">
      <label for="exampleFormControlTextarea1" class="lead">Enter your answer</label>
      <textarea name="answer" class="form-control" form="usrform" id="exampleFormControlTextarea1" rows="3" placeholder="Enter your answer...!"></textarea>
    </div>
    <form action="{% url 'forum:display_ans' question.id %}" id="usrform" method="POST"> <!--{#question.id#}save_answers-->
      {% csrf_token %}
      <input type="submit" class="btn btn-primary">
    </form>
    <br>
  </div>
  <div class="col-md-3"></div>
</div>
{% endblock content %}


<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">{{ answer.answer_text }}</p>
  </div>
</div>

templates/forum/display_questions.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1 class="title">Questions</h1>
    <br><br>
    <center>
      {% if all_questions %}
      <ul class="list-group">
        {% for question in all_questions %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <h4><a href="{% url 'forum:display_ans' question.id %}">{{question.question_text}}</a></h4>
          <!--<p class="text-right">asked by: {{question.asked_by}}</p>-->
          <p class="text-right">on: {{question.question_pub_date}}</p>
        </li>
        {%endfor%}
      </ul>
      {% else %}
      <h1>No questions to display!!!</h1>
      {% endif %}

    </center>

  </div>
  <div class="col-md-2"></div>
</div>
{% endblock content%}

<ul class="list-group">
  {% for question in all_questions %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <h3><a href="{% url 'forum:display_ans' question.id %}">{{question.question_text}}</a></h3>
    <span class="badge badge-primary badge-pill">14</span>
  </li>
  {%endfor%}
</ul>

templates/forum/ind.html
<form id="myform" class="fs-form fs-form-full" autocomplete="off" method="POST">{% csrf_token %}
	<ol class="fs-fields">
		<li>
			<label class="fs-field-label fs-anim-upper" for="q2" data-info="We won't send you spam, we promise...">What's your Name?</label>
			<input class="fs-anim-lower" id="q2" name="username" type="text" placeholder="John Doe" required pattern="[a-zA-Z0-9_ ]*" />
		</li>
		<li>
			<label class="fs-field-label fs-anim-upper" for="q2" data-info="We won't send you spam, we promise...">What's your email id?</label>
			<input class="fs-anim-lower" id="q2" name="email" type="email" placeholder="abc@gmail.com" required pattern="[A-Za-z][A-Za-z0-9._]+@[A-Za-z]+.[A-Za-z]+" />
		</li>
		<li>
			<label class="fs-field-label fs-anim-upper" for="q4">Mobile no.</label>
			<input class="fs-anim-lower" id="q4" name="phone" type="tel" placeholder="9876543210" required/>
		</li>
		<li>
			<label class="fs-field-label fs-anim-upper" for="q5" data-info="Password can only contain numbers and alphabet, with at least 8 characters.">Enter Password</label>
			<input class="fs-anim-lower" id="q5" name="password" type="password" placeholder="secret" required pattern="([a-zA-Z0-9]+){8,}" />
		</li>

		<li>
			<label class="fs-field-label fs-anim-upper" for="q4">College Name</label>
			<input class="fs-anim-lower" id="q7" type="text" name="college" placeholder="Vasavi College of Engg." required/>
		</li>
		<li>
			<label class="fs-field-label fs-anim-upper" for="q4">Roll no.</label>
			<input class="fs-anim-lower" id="q8" type="text" name="roll" placeholder="1602-1X-XXX-XXX" required/>
		</li>

	</ol>
	<!-- /fs-fields -->
	<button class="fs-submit" type="submit">Send answers</button>
</form>
<!-- /fs-form -->

templates/forum/start_page.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>
<div class="row" style="min-height:100%;max-width:100%;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <center>
      <input type="button" class="btn btn-primary" onclick="location.href='{% url 'forum:ask' %}';" value="Ask a question!" />
      <br><br>
      <input type="button" class="btn btn-primary" onclick="location.href='{% url 'forum:display_ques' %}';" value=" View questions" />
    </center>
  </div>
  <div class="col-md-3"></div>
</div>
{% endblock content%}